### ISSUE TITLE
Issue with `common_substrings`

### ISSUE THREAD

**Issue by rieck** [cceh/suffix-tree#3]
First of all, thanks a lot for providing this implementation of a generalized suffix tree. Kudos. 

I was playing a little bit with the function `common_substrings` and noticed some strange behavior. In certain cases, it misses substrings and presents duplicates:
```python
    strings = [ "abcxyz", "abcxyz", "xyzabc", "xyzabc" ]
    tree = Tree(dict(enumerate(strings)))
    for k, l, path in tree.common_substrings():
        print(k, l, path)
```

The output of this snippet is
```
    2 6 a b c x y z
    3 3 a b c
    4 3 a b c
```

In this example, we have four strings composed of `abc` and `xyz`. I was expecting `common_substrings` to return at least these two substrings. Furthermore, I cannot understand why the substring `abc` is returned twice with different (incorrect) $k$. What am I missing?

**Comment by MarcelloPerathoner** [comment]
The implementation of that function follows the exposition in "Gusfield, Dan. Algorithms on strings, trees, and sequences. 1997. Cambridge University Press."

(Let $K$ be the number of sequences in the tree.)

"**Definition** For each $k$ between $2$ and $K$, we define $l(k)$ to be the length of the *longest substring common to at least* $k$ *of the strings.*
        
"We want to compute a table of $K - 1$ entries, where entry $k$ gives $l(k)$ and also points to *one of the common substrings of that length.*" (my emphasis)
--- Gusfield1997, §7.6, page 127ff

The function reports that there are:
2 substrings of length 6 and gives an example as: abcxyz
3 substrings of length 3 and gives an example as: abc  (this is redundant)
4 substrings of length 4 and gives an example as: abc

This is probably not what you expected. I'll try to make it clearer in the docs what the function really does.

**Comment by rieck** [comment]
Thanks for the quick response. You are right, that is not what I expected. But your explanation makes sense. 👍 

I think I have this very book in my office, so I will read the chapter to understand what is going on. Maybe the code can be extended to also return the common substrings with their number of occurrences, e.g. (`abcxyz`:2, `xyzabc`:2, `abc`:4, `xyz`:4, and so on).

**Comment by MarcelloPerathoner** [comment]
Getting all common substrings is trivial: iterate over all internal nodes and return their string depth and C number. But this will return every suffix that is in the tree, it will also return `abcxy`:2, `bcxyz`:2, `abcx`:2, ... 

The hard part will be the post-processing to extract only the "interesting" strings.

**Comment by rieck** [comment]
Yes, this is what I had in mind. In principle, a simple traversal that spills out substrings above a given `min_k` and `l(k)`. There are different heuristics for filtering the returned strings. One is based on removing all common substrings that are part of another and have not much more support (occurences). Anyway, thanks.
